# Generated by Django 2.2.9 on 2020-01-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='landslideprob',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prob', models.DecimalField(decimal_places=5, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=20)),
                #('lon', models.DecimalField(decimal_places=7, max_digits=20)),
            ],
        ),
    ]
